spring:
  application:
    name: FoodApp

  datasource:
    url: ${DB_URL}

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwt:
    access-token:
      secret-key: ${JWT_ACCESS_SECRET}
      expiration: ${JWT_ACCESS_EXPIRATION}

    refresh-token:
      secret-key: ${JWT_REFRESH_SECRET}
      expiration: ${JWT_REFRESH_EXPIRATION}

  imagekit:
    public-key: ${IMAGEKIT_PUBLIC_KEY}
    private-key: ${IMAGEKIT_PRIVATE_KEY}
    url-endpoint: ${IMAGEKIT_URL_ENDPOINT}

  admin:
    email: ${APP_ADMIN_EMAIL}
    password: ${APP_ADMIN_PASSWORD}

  delivery-partner:
    email: ${APP_DELIVERY_EMAIL}
    password: ${APP_DELIVERY_PASSWORD}